### ISSUE TITLE
site out of date.

### ISSUE THREAD

**Issue by aarvid** [AccelerationNet/manifest-search-web#2]
The site appears to be out of date.  It does not contain recent quicklisp libraries.

**Comment by bobbysmith007** [comment]
This is true.  

Right after I made this site, someone released quickdocs http://quickdocs.org/, which had a nicer interface and seemed to be doing about as much as I was.  Since someone else had already solved this problem, I mostly abandoned my version of it.  I have changed the read me to note that.

If you find http://lisp-search.acceleration.net significantly more useful than quickdocs, please let me know and I will update it, but otherwise it seems like work someone else is already doing.

Cheers and thanks, I was not sure anyone had ever used lisp-search.acceleration.net

Russ

**Comment by aarvid** [comment]
Not a problem. I understand.  I maintain the sidebar for reddit's r/lisp subreddit. I added the link a few years ago along with quickdocs, zach's l1sp spec search and lispdoc.com (which has been down for the last month). Today, It was pointed out to me that your site was lacking recent libraries and not up-to-date.  I did not want to remove the link without consulting the current status.  

Thanks for replying promptly, you have made the decision to remove the link easier.
